### ISSUE TITLE
Crash when using pattern: #### #### #### #### ####

### ISSUE THREAD

**Issue by hnvn** [zsavely/PatternedTextWatcher#24]
When I try to use the pattern: `#### #### #### #### ####`, app crashes with trace log:

```
FATAL EXCEPTION: main
Process: vn.vimo.v2.debug, PID: 1635
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f01012d a=5}
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:482)
    at android.widget.TextView.setTextAppearance(TextView.java:2764)
    at android.support.design.widget.TextInputLayout.updateCounter(TextInputLayout.java:691)
    at android.support.design.widget.TextInputLayout.access$300(TextInputLayout.java:87)
    at android.support.design.widget.TextInputLayout$1.afterTextChanged(TextInputLayout.java:251)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:8017)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10182)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1043)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:560)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
    at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
    at android.widget.TextView.doKeyDown(TextView.java:6106)
    at android.widget.TextView.onKeyDown(TextView.java:5915)
    at android.view.KeyEvent.dispatch(KeyEvent.java:2661)
    at android.view.View.dispatchKeyEvent(View.java:9316)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:379)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1641)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2402)
    at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1734)
    at android.app.Activity.dispatchKeyEvent(Activity.java:2736)
    at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:533)
    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:53)
    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:254)
    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:53)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2317)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
```

**Comment by zsavely** [comment]
Could you specify the steps to reproduce your crash? I can't reproduce it with just `#### #### #### #### ####`. Moreover, there is no `PatternedTextWatcher` in your stack trace.

**Comment by hnvn** [comment]
Sorry, Your lib dont cause this error, I make a mistake when set up TextInputLayout.

Get Outlook for iOS




On Mon, Dec 12, 2016 at 7:01 PM +0700, "Savelii Zagurskii" <notifications@github.com> wrote:












Could you specify the build steps of your crash? I can't reproduce it with just #### #### #### #### ####. Moreover, there is no PatternedTextWatcher in your stack trace.
